apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-server-policy
  namespace: minigames
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: {{ .Values.server.ipBlock | quote }}
