serverName: minigame-server
image:
  repository: itzg/minecraft-server
  tag: latest
  pullPolicy: IfNotPresent

env:
  EULA: "TRUE"
  RABBITMQ_HOST: amqp.bungo.ca
  RABBITMQ_PORT: 5672

service:
  type: NodePort
  nodePort: null  # Let K8s assign randomly
  port: 25565

extraPodSpec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
