apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serverName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serverName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serverName }}
    spec:
      containers:
        - name: minecraft
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: EULA
              value: "{{ .Values.env.EULA }}"
            - name: SERVERNAME
              value: "{{.Values.serverName}}"
