apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serverName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.serverName }}
  ports:
    - name: minecraft
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort | default "null" }}
